// src/components/calendar/EventsListView.svelte
<script lang="ts">
import { format, eachDayOfInterval, startOfYear, endOfYear, startOfDay } from "date-fns";
import { ms, enUS } from "date-fns/locale";
import { CalendarDays, AlertCircle, CheckCircle2, Clock } from "lucide-svelte";
import { getAllEventsForDay } from "../../lib/holidays";
import { cn } from "../../lib/utils";

import { appSettings } from "../../state/settings.svelte";
import { themeState } from "../../state/theme.svelte";

let { currentDate, type } = $props<{
  currentDate: Date;
  type: "public" | "islamic" | "all";
}>();

const visualStyle = $derived(appSettings.settings.visualStyle);
const iconStroke = $derived(visualStyle === "glass" || visualStyle === "soft" ? 1.5 : 2.5);
const isMalay = $derived(appSettings.settings.language === "ms");

// Generate all events for the current year
const eventsList = $derived.by(() => {
  const yearStart = startOfYear(currentDate);
  const yearEnd = endOfYear(currentDate);
  const days = eachDayOfInterval({ start: yearStart, end: yearEnd });
  
  const list: { date: Date, title: string, type: 'public' | 'islamic', color?: string }[] = [];
  
  days.forEach(d => {
    const evs = getAllEventsForDay(d, null);
    evs.forEach(ev => {
      // Very basic filtering based on type string.
      const evType = ev.type;
      if (type === "all" || type === evType) {
        list.push({ date: d, title: ev.title, type: evType, color: ev.color });
      }
    });
  });
  
  return list;
});

const today = $derived(startOfDay(new Date()));
</script>

<div class="space-y-4">
  {#if eventsList.length === 0}
    <div class="flex flex-col items-center justify-center py-12 text-[var(--md-sys-color-on-surface-variant)] opacity-70">
      <CalendarDays size={48} strokeWidth={iconStroke} class="mb-4" />
      <p class="text-sm font-bold uppercase tracking-widest">{isMalay ? "Tiada acara ditemui" : "No events found"}</p>
    </div>
  {:else}
    {#each eventsList as event, i}
      {@const isPast = event.date < today}
      {@const isTodayEvent = event.date.getTime() === today.getTime()}
      <div 
        class={cn(
          "flex items-start gap-4 p-4 sm:p-5 transition-all duration-300",
          visualStyle === "retro" ? "border-2 border-[var(--md-sys-color-on-surface)]" : "bg-[var(--md-sys-color-surface-container)] rounded-[24px] border border-[var(--md-sys-color-outline)]/10",
          isPast ? "opacity-60 grayscale-[0.5]" : "",
          isTodayEvent ? "ring-2 ring-[var(--md-sys-color-primary)] ring-offset-2 ring-offset-[var(--md-sys-color-surface)]" : ""
        )}
      >
        <!-- Date Badge -->
        <div class={cn(
          "flex flex-col items-center justify-center min-w-[3.5rem] p-2 rounded-xl shrink-0",
          visualStyle === "retro" ? "border-2 border-[var(--md-sys-color-on-surface)]" : "bg-[var(--md-sys-color-surface-variant)] text-[var(--md-sys-color-on-surface-variant)]"
        )}>
          <span class="text-[10px] font-black uppercase tracking-widest">{format(event.date, "MMM", { locale: isMalay ? ms : enUS })}</span>
          <span class="text-xl sm:text-2xl font-black font-sans leading-none mt-0.5">{format(event.date, "d")}</span>
        </div>
        
        <!-- Details -->
        <div class="flex-1 min-w-0 pt-1">
          <div class="flex items-center gap-2 mb-1">
            {#if isTodayEvent}
              <span class="px-2 py-0.5 rounded-md bg-[var(--md-sys-color-tertiary-container)] text-[var(--md-sys-color-on-tertiary-container)] text-[9px] font-black uppercase tracking-wider shrink-0">
                {isMalay ? "HARI INI" : "TODAY"}
              </span>
            {/if}
            <span class="text-[10px] sm:text-xs font-bold text-[var(--md-sys-color-primary)] uppercase tracking-wider truncate">
              {event.type === 'public' ? (isMalay ? "Cuti Umum" : "Public Holiday") : (isMalay ? "Hari Islam" : "Islamic Date")}
            </span>
          </div>
          <h4 class={cn(
            "font-black text-sm sm:text-base leading-snug",
            isPast ? "text-[var(--md-sys-color-on-surface-variant)]" : "text-[var(--md-sys-color-on-surface)]"
          )}>
            {event.title}
          </h4>
          <p class="text-[11px] sm:text-xs text-[var(--md-sys-color-on-surface-variant)] mt-1 font-medium">
            {format(event.date, "EEEE, d MMMM yyyy", { locale: isMalay ? ms : enUS })}
          </p>
        </div>
        
        <!-- Status Icon -->
        <div class="shrink-0 pt-2 opacity-50">
          {#if isPast}
            <CheckCircle2 size={18} strokeWidth={iconStroke} />
          {:else if isTodayEvent}
            <AlertCircle size={18} strokeWidth={iconStroke} class="text-[var(--md-sys-color-tertiary)] opacity-100" />
          {:else}
            <Clock size={18} strokeWidth={iconStroke} />
          {/if}
        </div>
      </div>
    {/each}
  {/if}
</div>

// src/components/calendar/EventsListView.tsx
import { useState, useMemo } from "react";
import { format, eachDayOfInterval, startOfYear, endOfYear, startOfDay } from "date-fns";
import { ms, enUS } from "date-fns/locale";
import { motion } from "motion/react";
import { CalendarDays, AlertCircle, CheckCircle2, Clock } from "lucide-react";
import { getAllEventsForDay } from "../../lib/holidays";
import { cn } from "../../lib/utils";
import { useAppContext } from "../../AppContext";
import { useVisualStyle, useIconStroke } from "../../hooks/useVisualStyle";

interface EventsListViewProps {
  currentDate: Date;
  type: "public" | "islamic" | "all";
}

export function EventsListView({ currentDate, type }: EventsListViewProps) {
  const { t, settings } = useAppContext();
  const visualStyle = useVisualStyle();
  const iconStroke = useIconStroke();
  
  // Generate all events for the current year
  const eventsList = useMemo(() => {
    const yearStart = startOfYear(currentDate);
    const yearEnd = endOfYear(currentDate);
    const days = eachDayOfInterval({ start: yearStart, end: yearEnd });
    
    const list: { date: Date, title: string, type: 'public' | 'islamic', color?: string }[] = [];
    
    days.forEach(d => {
       const evts = getAllEventsForDay(d, null);
       evts.forEach(e => {
         if (type === "all" || e.type === type) {
            list.push({ date: d, title: e.title, type: e.type, color: e.color });
         }
       });
     });
     
    // Sort events by date
    return list.sort((a, b) => a.date.getTime() - b.date.getTime());
  }, [currentDate, type]);

  const today = startOfDay(new Date());

  if (eventsList.length === 0) {
    return (
      <div className={cn(
        "flex flex-col items-center justify-center p-12 text-center bg-[var(--md-sys-color-surface-container)] border border-[var(--md-sys-color-outline)]/12 rounded-3xl mt-4 select-none",
        visualStyle === "glass" && "bg-[var(--glass-bg)] backdrop-blur-md border-[var(--glass-border)] shadow-inner"
      )}>
        <AlertCircle size={36} className="text-[var(--md-sys-color-on-surface-variant)]/50 mb-3" />
        <p className="text-[var(--md-sys-color-on-surface-variant)] font-black text-sm uppercase tracking-widest">
          {t("noData")}
        </p>
      </div>
    );
  }

  return (
    <div className="flex flex-col gap-3.5 mt-4 pb-8 w-full max-w-4xl mx-auto">
      {eventsList.map((evt, idx) => {
        const isPast = evt.date < today;
        const isTodayEvent = evt.date.getTime() === today.getTime();
        
        return (
          <motion.div
            initial={{ opacity: 0, y: 12 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: Math.min(idx * 0.03, 0.4), type: "spring", stiffness: 350, damping: 25 }}
            key={`${evt.date.toISOString()}-${evt.title}`}
            className={cn(
               "flex flex-col sm:flex-row sm:items-center gap-4 sm:gap-5 p-4 sm:p-5 rounded-[22px] border transition-all duration-300 relative overflow-hidden select-none shadow-xs hover:shadow-md",
               isTodayEvent 
                 ? "bg-[var(--md-sys-color-primary-container)]/15 border-[var(--md-sys-color-primary)] ring-2 ring-[var(--md-sys-color-primary)]/20 shadow-md" 
                 : isPast 
                   ? "bg-[var(--md-sys-color-surface-variant)]/10 border-[var(--md-sys-color-outline)]/4 opacity-45 grayscale-[25%]"
                   : "bg-[var(--md-sys-color-surface-container-low)] border-[var(--md-sys-color-outline)]/8 hover:border-[var(--md-sys-color-primary)]/25",
               visualStyle === "glass" && "bg-[var(--glass-bg)]/40 backdrop-blur-md border-[var(--glass-border)]",
               visualStyle === "retro" && "border-2 border-[var(--md-sys-color-on-surface)] rounded-none shadow-[2px_2px_0px_0px_var(--md-sys-color-on-surface)]"
            )}
          >
            {isTodayEvent && <div className="absolute left-0 top-0 bottom-0 w-1 bg-[var(--md-sys-color-primary)] shadow-[0_0_8px_var(--md-sys-color-primary)]" />}

            {/* Date block */}
            <div className={cn("flex items-center gap-4 min-w-[110px] shrink-0", isPast && "opacity-75")}>
               <div className={cn(
                 "w-12 h-12 rounded-xl flex flex-col items-center justify-center shadow-xs shrink-0 select-none",
                 evt.type === 'public' 
                   ? "bg-[var(--md-sys-color-error-container)] text-[var(--md-sys-color-on-error-container)] border border-[var(--md-sys-color-error)]/10" 
                   : "bg-[var(--md-sys-color-primary-container)] text-[var(--md-sys-color-on-primary-container)] border border-[var(--md-sys-color-primary)]/10",
                 isPast && "bg-[var(--md-sys-color-surface-container-highest)] text-[var(--md-sys-color-on-surface-variant)] border-[var(--md-sys-color-outline)]/20"
               )}>
                 <span className="text-[8px] font-black uppercase tracking-wider">{format(evt.date, "MMM", { locale: settings.language === 'ms' ? ms : enUS })}</span>
                 <span className="text-xl font-black leading-none mt-0.5">{format(evt.date, "dd")}</span>
               </div>
               <div className="flex flex-col sm:hidden">
                 <span className="text-xs font-black opacity-80 uppercase tracking-widest text-[var(--md-sys-color-on-surface-variant)]">{format(evt.date, "EEEE", { locale: settings.language === 'ms' ? ms : enUS })}</span>
               </div>
            </div>
            
            {/* Week day label (desktop) */}
            <div className="hidden sm:block min-w-[90px] shrink-0">
              <span className="text-xs font-black opacity-70 uppercase tracking-widest text-[var(--md-sys-color-on-surface-variant)]">{format(evt.date, "EEEE", { locale: settings.language === 'ms' ? ms : enUS })}</span>
            </div>
            
            {/* Event Name & Badges */}
            <div className="flex flex-col gap-1.5 min-w-0 flex-1">
              <span className={cn(
                "font-black text-base sm:text-lg truncate leading-snug",
                isPast ? "text-[var(--md-sys-color-on-surface-variant)] line-through decoration-[var(--md-sys-color-outline)]/40 opacity-75" : "text-[var(--md-sys-color-on-surface)]"
              )}>
                {evt.title}
              </span>
              <div className="flex flex-wrap gap-1.5 items-center">
                 <span className={cn(
                   "px-2.5 py-0.5 rounded-full text-[9px] font-black uppercase tracking-wider border",
                   evt.type === 'public' 
                     ? isPast ? "bg-[var(--md-sys-color-error-container)]/40 text-[var(--md-sys-color-error)]/70 border-[var(--md-sys-color-error)]/30" : "bg-[var(--md-sys-color-error-container)]/20 text-[var(--md-sys-color-error)] border-[var(--md-sys-color-error)]/10" 
                     : isPast ? "bg-[var(--md-sys-color-tertiary-container)]/40 text-[var(--md-sys-color-tertiary)]/70 border-[var(--md-sys-color-tertiary)]/30" : "bg-[var(--md-sys-color-primary-container)]/20 text-[var(--md-sys-color-primary)] border-[var(--md-sys-color-primary)]/10"
                 )}>
                   {evt.type === 'public' ? t("publicHolidays") : t("islamicEvents")}
                 </span>
                 
                 {isTodayEvent ? (
                   <span className="px-2 py-0.5 rounded bg-[var(--md-sys-color-primary)] text-white text-[8px] font-black uppercase tracking-wider flex items-center gap-1 shadow-sm">
                     <CalendarDays size={10} /> {t("today")}
                   </span>
                 ) : isPast ? (
                   <span className="px-2 py-0.5 rounded bg-[var(--md-sys-color-surface-container-highest)] text-[var(--md-sys-color-on-surface-variant)] border border-[var(--md-sys-color-outline)]/20 text-[8px] font-black uppercase tracking-wider flex items-center gap-1">
                     <CheckCircle2 size={10} /> {t("passed")}
                   </span>
                 ) : (
                   <span className="px-2 py-0.5 rounded bg-[var(--md-sys-color-secondary-container)] text-[var(--md-sys-color-on-secondary-container)] border border-[var(--md-sys-color-secondary)]/20 text-[8px] font-black uppercase tracking-wider flex items-center gap-1">
                     <Clock size={10} strokeWidth={iconStroke} /> {t("upcoming")}
                   </span>
                 )}
              </div>
            </div>
          </motion.div>
        );
      })}
    </div>
  );
}
