// src/components/TvModeReminderCard.svelte
<script module lang="ts">
  import { audioSynthesizer } from "../lib/audio";

  export const playSynthesizedChime = (chimeType: 'bell' | 'chime' | 'gong' | 'notification', volumeVal: number) => {
    audioSynthesizer.play(chimeType, volumeVal).catch((e) => {
      console.warn("Failed to play synthesized chime:", e);
    });
  };
</script>

<script lang="ts">
  import { m3Fade as fade, m3Fly as fly, m3Slide as slide } from "../lib/transitions";
  import { Sparkles, Tv, Heart, Quote, AlertCircle } from "lucide-svelte";
  import type { TvModeReminder, TvModeReminderText, TvModeReminderImage } from "../types";
  import { cn } from "../lib/utils";

  let { reminder, assetUrls = {}, language = 'ms', isTvMode = false, nextPrayerTime = null } = $props<{
    reminder: TvModeReminder;
    assetUrls?: Record<string, string>;
    language?: 'ms' | 'en';
    isTvMode?: boolean;
    nextPrayerTime?: Date | null;
  }>();

  const getFontSizeClass = (size: string | undefined, isTvMode: boolean) => {
    const s = size || 'md';
    if (isTvMode) {
      switch (s) {
        case 'sm': return 'text-lg';
        case 'md': return 'text-xl sm:text-2xl';
        case 'lg': return 'text-2xl sm:text-3xl';
        case 'xl': return 'text-3xl sm:text-4xl';
        case '2xl': return 'text-4xl sm:text-5xl';
        case '3xl': return 'text-5xl sm:text-6xl';
        default: return 'text-2xl';
      }
    } else {
      switch (s) {
        case 'sm': return 'text-[9px]';
        case 'md': return 'text-[11px]';
        case 'lg': return 'text-xs';
        case 'xl': return 'text-sm';
        case '2xl': return 'text-base';
        case '3xl': return 'text-lg';
        default: return 'text-[11px]';
      }
    }
  };

  const getFontFamilyClass = (font: string | undefined) => {
    switch (font) {
      case 'serif': return 'font-serif italic';
      case 'mono': return 'font-mono';
      case 'sans':
      default:
        return 'font-sans';
    }
  };

  const getFontWeightClass = (weight: string | undefined) => {
    switch (weight) {
      case 'medium': return 'font-medium';
      case 'bold': return 'font-bold';
      case 'black': return 'font-black';
      case 'normal':
      default:
        return 'font-normal';
    }
  };

  const getTextAlignClass = (align: string | undefined) => {
    switch (align) {
      case 'left': return 'text-left';
      case 'right': return 'text-right';
      case 'justify': return 'text-justify';
      case 'center':
      default:
        return 'text-center';
    }
  };

  const getPresetStyles = (type: string, isTvMode: boolean) => {
    switch (type) {
      case 'hadith':
        return {
          bg: "bg-[var(--md-sys-color-primary-container)]/10 border-[var(--md-sys-color-primary)]/10",
          border: "border-l-4 border-l-[var(--md-sys-color-primary)]",
          glow: "rgba(168, 85, 247, 0.15)",
          watermark: "text-[var(--md-sys-color-primary)]/5"
        };
      case 'quran':
        return {
          bg: "bg-amber-500/5 border-amber-500/10",
          border: "border-l-4 border-l-amber-500",
          glow: "rgba(245, 158, 11, 0.15)",
          watermark: "text-amber-500/5"
        };
      case 'warning':
        return {
          bg: "bg-[var(--md-sys-color-error-container)]/5 border-[var(--md-sys-color-error)]/10",
          border: "border-l-4 border-l-[var(--md-sys-color-error)]",
          glow: "rgba(239, 68, 68, 0.15)",
          watermark: "text-[var(--md-sys-color-error)]/5"
        };
      case 'info':
        return {
          bg: "bg-blue-500/5 border-blue-500/10",
          border: "border-l-4 border-l-blue-500",
          glow: "rgba(59, 130, 246, 0.15)",
          watermark: "text-blue-500/5"
        };
      case 'donation':
        return {
          bg: "bg-rose-500/5 border-rose-500/10",
          border: "border-l-4 border-l-rose-500",
          glow: "rgba(244, 63, 94, 0.15)",
          watermark: "text-rose-500/5"
        };
      default:
        return {
          bg: "bg-[var(--md-sys-color-surface-container-low)] border-[var(--md-sys-color-outline)]/10",
          border: "",
          glow: "rgba(0, 0, 0, 0.05)",
          watermark: "text-[var(--md-sys-color-on-surface)]/2"
        };
    }
  };

  function customTransitionIn(node: Element, { type, duration }: { type: string; duration: number }) {
    switch (type) {
      case 'slide-left': return fly(node, { x: 100, duration });
      case 'slide-right': return fly(node, { x: -100, duration });
      case 'zoom': return scale(node, { start: 0.8, duration });
      case 'fade':
      default: return scale(node, { start: 0.96, duration });
    }
  }

  function customTransitionOut(node: Element, { type, duration }: { type: string; duration: number }) {
    switch (type) {
      case 'slide-left': return fly(node, { x: -100, duration });
      case 'slide-right': return fly(node, { x: 100, duration });
      case 'zoom': return scale(node, { start: 0.8, duration });
      case 'fade':
      default: return scale(node, { start: 0.96, duration });
    }
  }

  let timeLeft = $state<{ days: number; hours: number; minutes: number; seconds: number } | null>(null);

  $effect(() => {
    if (isTvMode && reminder.chime && reminder.chime !== 'none') {
      playSynthesizedChime(reminder.chime, reminder.chimeVolume ?? 80);
    }
  });

  function getNextFridayDateTime() {
    const now = new Date();
    const result = new Date(now);
    const day = now.getDay();
    const targetHour = 13;
    
    let daysToAdd = (5 - day + 7) % 7;
    if (daysToAdd === 0) {
      if (now.getHours() >= targetHour) {
        daysToAdd = 7;
      }
    }
    
    result.setDate(now.getDate() + daysToAdd);
    result.setHours(targetHour, 0, 0, 0);
    return result;
  }

  $effect(() => {
    if (!reminder.countdownTarget) {
      timeLeft = null;
      return;
    }
    
    const calculateTimeLeft = () => {
      let targetTime = 0;
      if (reminder.countdownTarget === "next-prayer") {
        if (!nextPrayerTime) return null;
        targetTime = new Date(nextPrayerTime).getTime();
      } else if (reminder.countdownTarget === "next-friday") {
        targetTime = getNextFridayDateTime().getTime();
      } else {
        targetTime = new Date(reminder.countdownTarget!).getTime();
      }

      if (isNaN(targetTime) || targetTime <= 0) return null;
      
      const difference = targetTime - Date.now();
      if (difference <= 0) {
        return { days: 0, hours: 0, minutes: 0, seconds: 0 };
      }
      return {
        days: Math.floor(difference / (1000 * 60 * 60 * 24)),
        hours: Math.floor((difference / (1000 * 60 * 60)) % 24),
        minutes: Math.floor((difference / 1000 / 60) % 60),
        seconds: Math.floor((difference / 1000) % 60),
      };
    };

    const initial = calculateTimeLeft();
    timeLeft = initial;
    if (!initial) return;

    const timer = setInterval(() => {
      const updated = calculateTimeLeft();
      if (updated) {
        timeLeft = updated;
      }
    }, 1000);

    return () => clearInterval(timer);
  });

  let isLegacy = $derived(!reminder.texts);

  let texts = $derived.by<TvModeReminderText[]>(() => {
    if (reminder.texts && reminder.texts.length > 0) return reminder.texts;
    const legacyTexts: TvModeReminderText[] = [];
    if (reminder.title && reminder.type !== 'donation') {
      legacyTexts.push({
        id: 'legacy-ref',
        content: reminder.title,
        type: 'subtitle',
        size: 'lg',
        font: 'sans',
        align: 'center',
        weight: 'bold'
      });
    }
    if (reminder.text) {
      legacyTexts.push({
        id: 'legacy-body',
        content: reminder.text,
        type: 'body',
        size: 'md',
        font: reminder.type === 'warning' ? 'sans' : 'serif',
        align: 'center',
        weight: reminder.type === 'warning' ? 'bold' : 'normal'
      });
    }
    if (reminder.title && reminder.type === 'donation') {
      legacyTexts.push({
        id: 'legacy-title',
        content: reminder.title,
        type: 'title',
        size: 'xl',
        font: 'sans',
        align: 'left',
        weight: 'black'
      });
    }
    return legacyTexts;
  });

  let images = $derived.by<TvModeReminderImage[]>(() => {
    if (reminder.images && reminder.images.length > 0) return reminder.images;
    if (reminder.imageUrl) {
      return [{
        id: 'legacy-img',
        url: reminder.imageUrl,
        position: reminder.type === 'donation' ? 'right' : 'background',
        width: reminder.type === 'donation' ? 40 : 100,
        shape: reminder.type === 'donation' ? 'rounded' : 'original',
        blendMode: 'none',
        padding: 0
      }];
    }
    return [];
  });

  let layout = $derived(reminder.layout || (reminder.type === 'donation' ? 'flex-row' : 'flex-col'));
  let gap = $derived(reminder.gap ?? 6);
  let bgPattern = $derived(reminder.bgPattern || 'none');
  let bgPatternOpacity = $derived(reminder.bgPatternOpacity ?? 0.07);
  let borderHighlight = $derived(reminder.borderHighlight || (isLegacy ? 'left' : 'none'));

  let presets = $derived(getPresetStyles(reminder.type, isTvMode));

  let cardStyle = $derived.by(() => {
    const s: string[] = [];
    if (reminder.bgColor) s.push(`background-color: ${reminder.bgColor}`);
    if (reminder.bgGradient) s.push(`background-image: ${reminder.bgGradient}`);
    if (reminder.borderColor) s.push(`border-color: ${reminder.borderColor}`);
    if (reminder.bgGlowColor) {
      s.push(`box-shadow: 0 0 25px ${reminder.bgGlowColor}`);
    } else if (reminder.type !== 'custom') {
      s.push(`box-shadow: 0 10px 40px -10px ${presets.glow}`);
    }
    return s.join('; ');
  });

  let borderClasses = $derived.by(() => {
    let classes = "border border-[var(--md-sys-color-outline)]/10";
    if (borderHighlight !== 'none') {
      const highlightColorClass = reminder.borderColor 
        ? "" 
        : (reminder.type === 'hadith' ? "border-[var(--md-sys-color-primary)]" :
           reminder.type === 'quran' ? "border-amber-500" :
           reminder.type === 'warning' ? "border-[var(--md-sys-color-error)]" :
           reminder.type === 'info' ? "border-blue-500" :
           reminder.type === 'donation' ? "border-rose-500" : "border-[var(--md-sys-color-primary)]");

      switch (borderHighlight) {
        case 'left':
          classes = cn("border-l-4 border-y border-r border-[var(--md-sys-color-outline)]/10 tv-card-border-left", highlightColorClass);
          break;
        case 'top':
          classes = cn("border-t-4 border-x border-b border-[var(--md-sys-color-outline)]/10 tv-card-border-top", highlightColorClass);
          break;
        case 'right':
          classes = cn("border-r-4 border-y border-l border-[var(--md-sys-color-outline)]/10 tv-card-border-right", highlightColorClass);
          break;
        case 'bottom':
          classes = cn("border-b-4 border-x border-t border-[var(--md-sys-color-outline)]/10 tv-card-border-bottom", highlightColorClass);
          break;
        case 'all':
          classes = cn("border-4 border-[var(--md-sys-color-outline)]/10 tv-card-border-all", highlightColorClass);
          break;
      }
    }
    return classes;
  });

  let bgImages = $derived(images.filter(img => img.position === 'background'));
  let flowImages = $derived(images.filter(img => img.position !== 'background'));

  function resolveImgSrc(img: TvModeReminderImage) {
    if (img.isUploaded && img.assetKey) {
      return assetUrls[img.assetKey] || img.url;
    }
    return img.url;
  }

  let leftImages = $derived(flowImages.filter(img => img.position === 'left'));
  let rightImages = $derived(flowImages.filter(img => img.position === 'right'));
  let topImages = $derived(flowImages.filter(img => img.position === 'top'));
  let bottomImages = $derived(flowImages.filter(img => img.position === 'bottom'));
</script>

<style>
  @keyframes card-marquee-scroll {
    0% { transform: translateX(0%); }
    100% { transform: translateX(-50%); }
  }
  :global(.card-marquee-container) {
    overflow: hidden;
    white-space: nowrap;
    width: 100%;
    display: block;
  }
  :global(.card-marquee-content) {
    display: inline-block;
    animation: card-marquee-scroll 20s linear infinite;
    will-change: transform;
  }
  @keyframes float-particle-up {
    0% { transform: translateY(110%) scale(0.7); opacity: 0; }
    20% { opacity: 0.35; }
    80% { opacity: 0.35; }
    100% { transform: translateY(-20%) scale(1.1); opacity: 0; }
  }
  :global(.floating-particle) {
    position: absolute;
    bottom: -40px;
    background: radial-gradient(circle, rgba(255,255,255,0.14) 0%, rgba(255,255,255,0) 70%);
    border-radius: 50%;
    pointer-events: none;
    z-index: 1;
    animation: float-particle-up linear infinite;
  }
  @keyframes ambient-pulse-slow {
    0% { transform: scale(1) translate(0px, 0px); opacity: 0.06; }
    50% { transform: scale(1.15) translate(25px, -20px); opacity: 0.14; }
    100% { transform: scale(1) translate(0px, 0px); opacity: 0.06; }
  }
  @keyframes ambient-pulse-slow-reverse {
    0% { transform: scale(1.1) translate(0px, 0px); opacity: 0.04; }
    50% { transform: scale(0.95) translate(-30px, 15px); opacity: 0.11; }
    100% { transform: scale(1.1) translate(0px, 0px); opacity: 0.04; }
  }
  :global(.ambient-pulse-blob-1) {
    position: absolute;
    width: 60%;
    height: 60%;
    top: 5%;
    left: 5%;
    border-radius: 40% 60% 70% 30% / 40% 50% 60% 50%;
    filter: blur(50px);
    animation: ambient-pulse-slow 20s ease-in-out infinite;
    z-index: 0;
    pointer-events: none;
  }
  :global(.ambient-pulse-blob-2) {
    position: absolute;
    width: 60%;
    height: 60%;
    bottom: 5%;
    right: 5%;
    border-radius: 60% 40% 30% 70% / 50% 60% 50% 40%;
    filter: blur(50px);
    animation: ambient-pulse-slow-reverse 26s ease-in-out infinite;
    z-index: 0;
    pointer-events: none;
  }
</style>

{#snippet imageItem(img: TvModeReminderImage)}
  {@const src = resolveImgSrc(img)}
  {@const imgStyle = [
    img.width ? `width: ${img.width}%` : '',
    img.height ? `max-height: ${isTvMode ? img.height * 2.2 : img.height}px` : '',
    img.padding ? `padding: ${img.padding}px` : ''
  ].filter(Boolean).join('; ')}
  {#if src}
    <div
      class={cn(
        "shrink-0 flex items-center justify-center transition-all bg-white overflow-hidden shadow-sm",
        img.shape === 'circle' ? "rounded-full" :
        img.shape === 'rounded' ? (isTvMode ? "rounded-3xl" : "rounded-xl") :
        img.shape === 'square' ? "rounded-none" : "rounded-xl",
        img.align === 'start' ? "self-start" :
        img.align === 'end' ? "self-end" : "self-center",
        img.blendMode && img.blendMode !== 'none' ? `mix-blend-${img.blendMode}` : ""
      )}
      style={imgStyle}
    >
      <img
        src={src}
        alt="Reminder Media"
        class="w-full h-full object-contain pointer-events-none"
      />
    </div>
  {/if}
{/snippet}

{#key reminder.id}
  <div
    in:customTransitionIn={{ type: reminder.transition || 'fade', duration: 450 }}
    out:customTransitionOut={{ type: reminder.transition || 'fade', duration: 450 }}
    class={cn(
      "tv-reminder-card-container flex-grow flex p-6 sm:p-10 rounded-[36px] relative overflow-hidden transition-all duration-500 select-none min-h-[140px] items-center justify-center",
      reminder.bgColor || reminder.bgGradient ? "" : presets.bg,
      borderClasses
    )}
    style={cardStyle}
  >
    <!-- 1. Background Pattern Overlay -->
    {#if bgPattern !== 'none'}
      <div 
        class={cn(
          "absolute inset-0 pointer-events-none z-0 transition-opacity",
          bgPattern === 'islamic' ? "islamic-pattern-overlay pattern-islamic" :
          bgPattern === 'dots' ? "pattern-dots bg-[radial-gradient(ellipse_at_center,_var(--tw-gradient-stops))] from-neutral-500/10 via-transparent to-transparent bg-[size:10px_10px]" :
          "pattern-grid bg-[linear-gradient(to_right,#80808012_1px,transparent_1px),linear-gradient(to_bottom,#80808012_1px,transparent_1px)] bg-[size:20px_20px]"
        )}
        style="opacity: {bgPatternOpacity}"
      ></div>
    {/if}

    <!-- 1b. Ambient Visual Effects -->
    {#if reminder.bgEffect === 'floating-particles'}
      <div class="absolute inset-0 overflow-hidden pointer-events-none z-0 effect-floating-particles">
        {#each Array.from({ length: 8 }) as _, idx}
          {@const size = 30 + (idx * 15) % 65}
          {@const left = 5 + (idx * 13) % 90}
          {@const duration = 12 + (idx * 3) % 13}
          {@const delay = (idx * 1.5) % 8}
          <div 
            class="floating-particle"
            style="width: {size}px; height: {size}px; left: {left}%; animation-duration: {duration}s; animation-delay: {delay}s;"
          ></div>
        {/each}
      </div>
    {/if}

    {#if reminder.bgEffect === 'ambient-pulses'}
      <div class="absolute inset-0 overflow-hidden pointer-events-none z-0 effect-ambient-pulses">
        <div 
          class="ambient-pulse-blob-1 bg-[var(--md-sys-color-primary)]"
          style={reminder.borderColor ? `background: ${reminder.borderColor}` : ""}
        ></div>
        <div 
          class="ambient-pulse-blob-2 bg-[var(--md-sys-color-secondary-container)]"
          style={reminder.bgGlowColor ? `background: ${reminder.bgGlowColor}` : ""}
        ></div>
      </div>
    {/if}

    <!-- 2. Background Uploaded/URL Images -->
    {#each bgImages as img (img.id)}
      {@const src = resolveImgSrc(img)}
      {@const bgImgStyle = `opacity: ${img.width ? img.width / 100 : 0.15};${img.padding ? ` padding: ${img.padding}px;` : ''}`}
      {#if src}
        <img
          src={src}
          alt="Background pattern"
          class={cn(
            "absolute inset-0 w-full h-full object-cover pointer-events-none z-0 transition-all",
            img.blendMode && img.blendMode !== 'none' ? `mix-blend-${img.blendMode}` : "opacity-15",
            img.shape === 'circle' ? "rounded-full" : ""
          )}
          style={bgImgStyle}
        />
      {/if}
    {/each}

    <!-- 3. Watermark -->
    {#if bgImages.length === 0}
      {@const iconSize = isTvMode ? 140 : 64}
      {@const iconClass = cn(presets.watermark, "absolute -right-2 -top-2 pointer-events-none rotate-180 z-0 opacity-40")}
      {#if reminder.type === 'hadith'}
        <Quote size={iconSize} class={iconClass} />
      {:else if reminder.type === 'quran'}
        <Sparkles size={iconSize} class={iconClass} />
      {:else if reminder.type === 'warning'}
        <AlertCircle size={iconSize} class={iconClass} />
      {:else if reminder.type === 'info'}
        <Tv size={iconSize} class={iconClass} />
      {:else if reminder.type === 'donation'}
        <Heart size={iconSize} class={iconClass} />
      {/if}
    {/if}

    <!-- 5. Main Content Layout (Texts and Flow Images) -->
    <div 
      class={cn(
        "w-full h-full flex relative z-10 items-center justify-center",
        layout === 'flex-row' ? "flex-row" :
        layout === 'flex-row-reverse' ? "flex-row-reverse" :
        layout === 'flex-col-reverse' ? "flex-col-reverse" :
        layout === 'overlay' ? "relative" : "flex-col",
        `gap-${gap}`
      )}
    >
      <!-- Left media block -->
      {#if leftImages.length > 0}
        <div class="flex flex-col gap-2 shrink-0">
          {#each leftImages as img (img.id)}
            {@render imageItem(img)}
          {/each}
        </div>
      {/if}

      <!-- Vertical group for Top images, Texts, and Bottom images -->
      <div class="flex-grow flex flex-col justify-center w-full gap-3">
        {#if topImages.length > 0}
          <div class="flex flex-row gap-2 justify-center flex-wrap">
            {#each topImages as img (img.id)}
              {@render imageItem(img)}
            {/each}
          </div>
        {/if}

        <!-- Texts blocks list -->
        <div class="space-y-2 w-full flex flex-col justify-center">
          {#each texts as t (t.id)}
            {@const isTitle = t.type === 'title'}
            {@const isSubtitle = t.type === 'subtitle'}
            {@const isCaption = t.type === 'caption'}
            
            {@const defaultColorClass = t.color ? "" : (
              isTitle ? "text-[var(--md-sys-color-on-surface)]" :
              isSubtitle ? "text-[var(--md-sys-color-primary)] dark:text-[var(--md-sys-color-secondary)]" :
              isCaption ? "text-[var(--md-sys-color-on-surface-variant)]/60" :
              "text-[var(--md-sys-color-on-surface-variant)]"
            )}
            
            {@const textStyle = `${t.color ? `color: ${t.color};` : ''}${t.glow ? `text-shadow: 0 0 10px ${t.color || 'var(--md-sys-color-primary)'}, 0 0 20px ${t.color || 'var(--md-sys-color-primary)'};` : ''}`}

            {#if t.marquee}
              <div 
                class={cn(
                  "card-marquee-container",
                  getFontSizeClass(t.size, isTvMode),
                  getFontFamilyClass(t.font),
                  defaultColorClass,
                  isTitle ? "tracking-wide uppercase mb-1 font-black" :
                  isSubtitle ? "tracking-widest uppercase mb-1" : "",
                  getFontWeightClass(t.weight)
                )}
                style={textStyle}
              >
                <div class="card-marquee-content">
                  {t.content}
                  <span class="opacity-40 px-12">&bull;</span>
                  {t.content}
                  <span class="opacity-40 px-12">&bull;</span>
                </div>
              </div>
            {:else}
              <div
                class={cn(
                  getFontSizeClass(t.size, isTvMode),
                  getFontFamilyClass(t.font),
                  getTextAlignClass(t.align),
                  defaultColorClass,
                  isTitle ? "tracking-wide uppercase mb-1 font-black" :
                  isSubtitle ? "tracking-widest uppercase mb-1" : "",
                  getFontWeightClass(t.weight)
                )}
                style={textStyle}
              >
                {t.content}
              </div>
            {/if}
          {/each}
        </div>

        <!-- Countdown Widget -->
        {#if timeLeft}
          <div class={cn("flex flex-col items-center mt-4 mb-2 z-10 w-full", isTvMode ? "gap-4" : "gap-1")}>
            {#if reminder.countdownLabel}
              <div class={cn(
                "font-sans font-medium text-center opacity-85 tracking-wide",
                isTvMode ? "text-xl" : "text-[10px]"
              )}>
                {reminder.countdownLabel}
              </div>
            {/if}
            <div class="flex flex-row items-center justify-center gap-2">
              {#each [
                { value: timeLeft.days, label: language === 'ms' ? 'Hari' : 'Days' },
                { value: timeLeft.hours, label: language === 'ms' ? 'Jam' : 'Hours' },
                { value: timeLeft.minutes, label: language === 'ms' ? 'Min' : 'Mins' },
                { value: timeLeft.seconds, label: language === 'ms' ? 'Saat' : 'Secs' },
              ] as item, idx}
                <div class={cn(
                  "flex flex-col items-center justify-center bg-black/15 dark:bg-white/10 border border-white/10 rounded-2xl shadow-inner",
                  isTvMode ? "p-3 min-w-[100px] h-[90px]" : "p-1 min-w-[44px] h-[36px]"
                )}>
                  <span class={cn("font-mono font-bold leading-none", isTvMode ? "text-3xl" : "text-sm")}>
                    {String(item.value).padStart(2, '0')}
                  </span>
                  <span class={cn("font-sans uppercase opacity-60 tracking-wider font-semibold", isTvMode ? "text-[10px] mt-1" : "text-[6px] mt-0.5")}>
                    {item.label}
                  </span>
                </div>
                {#if idx < 3}
                  <span class={cn("font-mono font-bold opacity-60", isTvMode ? "text-3xl mx-1" : "text-sm mx-0.5")}>
                    :
                  </span>
                {/if}
              {/each}
            </div>
          </div>
        {/if}

        {#if bottomImages.length > 0}
          <div class="flex flex-row gap-2 justify-center flex-wrap">
            {#each bottomImages as img (img.id)}
              {@render imageItem(img)}
            {/each}
          </div>
        {/if}
      </div>

      <!-- Right media block -->
      {#if rightImages.length > 0}
        <div class="flex flex-col gap-2 shrink-0">
          {#each rightImages as img (img.id)}
            {@render imageItem(img)}
          {/each}
        </div>
      {/if}
    </div>
  </div>
{/key}

// src/components/TvModeReminderCard.tsx
import React from "react";
import { motion } from "motion/react";
import {
  BookOpen,
  Sparkles,
  VolumeX,
  Tv,
  Heart,
  Quote,
  AlertCircle
} from "lucide-react";
import { TvModeReminder, TvModeReminderText, TvModeReminderImage } from "../types";
import { cn } from "../lib/utils";

interface TvModeReminderCardProps {
  reminder: TvModeReminder;
  assetUrls?: Record<string, string>;
  language?: 'ms' | 'en';
  isTvMode?: boolean; // Toggles text sizes between widescreen TV and settings preview
}

// Map sizes to Tailwind font sizes based on display mode
const getFontSizeClass = (size: string | undefined, isTvMode: boolean) => {
  const s = size || 'md';
  if (isTvMode) {
    switch (s) {
      case 'sm': return 'text-lg';
      case 'md': return 'text-xl sm:text-2xl';
      case 'lg': return 'text-2xl sm:text-3xl';
      case 'xl': return 'text-3xl sm:text-4xl';
      case '2xl': return 'text-4xl sm:text-5xl';
      case '3xl': return 'text-5xl sm:text-6xl';
      default: return 'text-2xl';
    }
  } else {
    switch (s) {
      case 'sm': return 'text-[9px]';
      case 'md': return 'text-[11px]';
      case 'lg': return 'text-xs';
      case 'xl': return 'text-sm';
      case '2xl': return 'text-base';
      case '3xl': return 'text-lg';
      default: return 'text-[11px]';
    }
  }
};

const getFontFamilyClass = (font: string | undefined) => {
  switch (font) {
    case 'serif': return 'font-serif italic';
    case 'mono': return 'font-mono';
    case 'sans':
    default:
      return 'font-sans';
  }
};

const getFontWeightClass = (weight: string | undefined) => {
  switch (weight) {
    case 'medium': return 'font-medium';
    case 'bold': return 'font-bold';
    case 'black': return 'font-black';
    case 'normal':
    default:
      return 'font-normal';
  }
};

const getTextAlignClass = (align: string | undefined) => {
  switch (align) {
    case 'left': return 'text-left';
    case 'right': return 'text-right';
    case 'justify': return 'text-justify';
    case 'center':
    default:
      return 'text-center';
  }
};

// Preset colors and border highlights
const getPresetStyles = (type: string, isTvMode: boolean) => {
  switch (type) {
    case 'hadith':
      return {
        bg: "bg-[var(--md-sys-color-primary-container)]/10 border-[var(--md-sys-color-primary)]/10",
        border: "border-l-4 border-l-[var(--md-sys-color-primary)]",
        glow: "rgba(168, 85, 247, 0.15)",
        watermark: "text-[var(--md-sys-color-primary)]/5"
      };
    case 'quran':
      return {
        bg: "bg-amber-500/5 border-amber-500/10",
        border: "border-l-4 border-l-amber-500",
        glow: "rgba(245, 158, 11, 0.15)",
        watermark: "text-amber-500/5"
      };
    case 'warning':
      return {
        bg: "bg-[var(--md-sys-color-error-container)]/5 border-[var(--md-sys-color-error)]/10",
        border: "border-l-4 border-l-[var(--md-sys-color-error)]",
        glow: "rgba(239, 68, 68, 0.15)",
        watermark: "text-[var(--md-sys-color-error)]/5"
      };
    case 'info':
      return {
        bg: "bg-blue-500/5 border-blue-500/10",
        border: "border-l-4 border-l-blue-500",
        glow: "rgba(59, 130, 246, 0.15)",
        watermark: "text-blue-500/5"
      };
    case 'donation':
      return {
        bg: "bg-rose-500/5 border-rose-500/10",
        border: "border-l-4 border-l-rose-500",
        glow: "rgba(244, 63, 94, 0.15)",
        watermark: "text-rose-500/5"
      };
    default:
      return {
        bg: "bg-[var(--md-sys-color-surface-container-low)] border-[var(--md-sys-color-outline)]/10",
        border: "",
        glow: "rgba(0, 0, 0, 0.05)",
        watermark: "text-[var(--md-sys-color-on-surface)]/2"
      };
  }
};

export function TvModeReminderCard({ reminder, assetUrls = {}, language = 'ms', isTvMode = false }: TvModeReminderCardProps) {
  const [timeLeft, setTimeLeft] = React.useState<{ days: number; hours: number; minutes: number; seconds: number } | null>(null);

  React.useEffect(() => {
    if (!reminder.countdownTarget) {
      setTimeLeft(null);
      return;
    }
    
    const calculateTimeLeft = () => {
      const targetTime = new Date(reminder.countdownTarget!).getTime();
      if (isNaN(targetTime)) return null;
      
      const difference = targetTime - Date.now();
      if (difference <= 0) {
        return { days: 0, hours: 0, minutes: 0, seconds: 0 };
      }
      return {
        days: Math.floor(difference / (1000 * 60 * 60 * 24)),
        hours: Math.floor((difference / (1000 * 60 * 60)) % 24),
        minutes: Math.floor((difference / 1000 / 60) % 60),
        seconds: Math.floor((difference / 1000) % 60),
      };
    };

    const initial = calculateTimeLeft();
    setTimeLeft(initial);
    if (!initial) return;

    const timer = setInterval(() => {
      const updated = calculateTimeLeft();
      if (updated) {
        setTimeLeft(updated);
      }
    }, 1000);

    return () => clearInterval(timer);
  }, [reminder.countdownTarget]);

  // Normalize layout properties
  const isLegacy = !reminder.texts;
  
  // 1. Normalize Texts
  const texts = React.useMemo<TvModeReminderText[]>(() => {
    if (reminder.texts && reminder.texts.length > 0) return reminder.texts;
    // Legacy fallback
    const legacyTexts: TvModeReminderText[] = [];
    if (reminder.title && reminder.type !== 'donation') {
      legacyTexts.push({
        id: 'legacy-ref',
        content: reminder.title,
        type: 'subtitle',
        size: 'lg',
        font: 'sans',
        align: 'center',
        weight: 'bold'
      });
    }
    if (reminder.text) {
      legacyTexts.push({
        id: 'legacy-body',
        content: reminder.text,
        type: 'body',
        size: 'md',
        font: reminder.type === 'warning' ? 'sans' : 'serif',
        align: 'center',
        weight: reminder.type === 'warning' ? 'bold' : 'normal'
      });
    }
    if (reminder.title && reminder.type === 'donation') {
      legacyTexts.push({
        id: 'legacy-title',
        content: reminder.title,
        type: 'title',
        size: 'xl',
        font: 'sans',
        align: 'left',
        weight: 'black'
      });
    }
    return legacyTexts;
  }, [reminder.texts, reminder.title, reminder.text, reminder.type]);

  // 2. Normalize Images
  const images = React.useMemo<TvModeReminderImage[]>(() => {
    if (reminder.images && reminder.images.length > 0) return reminder.images;
    // Legacy fallback
    if (reminder.imageUrl) {
      return [{
        id: 'legacy-img',
        url: reminder.imageUrl,
        position: reminder.type === 'donation' ? 'right' : 'background',
        width: reminder.type === 'donation' ? 40 : 100,
        shape: reminder.type === 'donation' ? 'rounded' : 'original',
        blendMode: 'none',
        padding: 0
      }];
    }
    return [];
  }, [reminder.images, reminder.imageUrl, reminder.type]);

  const layout = reminder.layout || (reminder.type === 'donation' ? 'flex-row' : 'flex-col');
  const gap = reminder.gap ?? 6;
  const bgPattern = reminder.bgPattern || 'none';
  const bgPatternOpacity = reminder.bgPatternOpacity ?? 0.07;
  const borderHighlight = reminder.borderHighlight || (isLegacy ? 'left' : 'none');

  // Load preset base styles
  const presets = getPresetStyles(reminder.type, isTvMode);

  // Background inline styles
  const cardStyle: React.CSSProperties = {};
  if (reminder.bgColor) {
    cardStyle.backgroundColor = reminder.bgColor;
  }
  if (reminder.bgGradient) {
    // Custom gradient
    cardStyle.backgroundImage = reminder.bgGradient;
  }

  // Glow shadow inline styles
  if (reminder.bgGlowColor) {
    cardStyle.boxShadow = `0 10px 40px -10px ${reminder.bgGlowColor}`;
  } else if (reminder.type !== 'custom') {
    cardStyle.boxShadow = `0 10px 40px -10px ${presets.glow}`;
  }

  // Border highlight classes
  let borderClasses = "border border-[var(--md-sys-color-outline)]/10";
  if (borderHighlight !== 'none') {
    const highlightColorClass = reminder.borderColor 
      ? "" 
      : (reminder.type === 'hadith' ? "border-[var(--md-sys-color-primary)]" :
         reminder.type === 'quran' ? "border-amber-500" :
         reminder.type === 'warning' ? "border-[var(--md-sys-color-error)]" :
         reminder.type === 'info' ? "border-blue-500" :
         reminder.type === 'donation' ? "border-rose-500" : "border-[var(--md-sys-color-primary)]");

    switch (borderHighlight) {
      case 'left':
        borderClasses = cn("border-l-4 border-y border-r border-[var(--md-sys-color-outline)]/10", highlightColorClass);
        break;
      case 'top':
        borderClasses = cn("border-t-4 border-x border-b border-[var(--md-sys-color-outline)]/10", highlightColorClass);
        break;
      case 'right':
        borderClasses = cn("border-r-4 border-y border-l border-[var(--md-sys-color-outline)]/10", highlightColorClass);
        break;
      case 'bottom':
        borderClasses = cn("border-b-4 border-x border-t border-[var(--md-sys-color-outline)]/10", highlightColorClass);
        break;
      case 'all':
        borderClasses = cn("border-4 border-[var(--md-sys-color-outline)]/10", highlightColorClass);
        break;
    }
  }

  // Separate background images from layout flow images
  const bgImages = images.filter(img => img.position === 'background');
  const flowImages = images.filter(img => img.position !== 'background');

  // Helper to resolve image source URL
  const resolveImgSrc = (img: typeof images[0]) => {
    if (img.isUploaded && img.assetKey) {
      return assetUrls[img.assetKey] || img.url;
    }
    return img.url;
  };

  // Preset watermark icon
  const renderWatermark = () => {
    // Only render watermarks if it's a standard category and has no background image
    if (bgImages.length > 0) return null;
    
    const iconSize = isTvMode ? 140 : 64;
    const iconClass = cn(presets.watermark, "absolute -right-2 -top-2 pointer-events-none rotate-180 z-0 opacity-40");
    
    switch (reminder.type) {
      case 'hadith':
        return <Quote size={iconSize} className={iconClass} />;
      case 'quran':
        return <Sparkles size={iconSize} className={iconClass} />;
      case 'warning':
        return <AlertCircle size={iconSize} className={iconClass} />;
      case 'info':
        return <Tv size={iconSize} className={iconClass} />;
      case 'donation':
        return <Heart size={iconSize} className={iconClass} />;
      default:
        return null;
    }
  };

  // Style gap mappings
  const gapClass = `gap-${gap}`;

  // Image layout components (left/right/top/bottom)
  const leftImages = flowImages.filter(img => img.position === 'left');
  const rightImages = flowImages.filter(img => img.position === 'right');
  const topImages = flowImages.filter(img => img.position === 'top');
  const bottomImages = flowImages.filter(img => img.position === 'bottom');

  const renderImageItem = (img: typeof images[0]) => {
    const src = resolveImgSrc(img);
    if (!src) return null;

    const imgStyle: React.CSSProperties = {};
    if (img.width) {
      imgStyle.width = `${img.width}%`;
    }
    if (img.height) {
      imgStyle.maxHeight = isTvMode ? `${img.height * 2.2}px` : `${img.height}px`;
    }
    if (img.padding) {
      imgStyle.padding = `${img.padding}px`;
    }

    return (
      <div
        key={img.id}
        className={cn(
          "shrink-0 flex items-center justify-center transition-all bg-white overflow-hidden shadow-sm",
          img.shape === 'circle' ? "rounded-full" :
          img.shape === 'rounded' ? (isTvMode ? "rounded-3xl" : "rounded-xl") :
          img.shape === 'square' ? "rounded-none" : "rounded-xl",
          img.align === 'start' ? "self-start" :
          img.align === 'end' ? "self-end" : "self-center",
          img.blendMode && img.blendMode !== 'none' ? `mix-blend-${img.blendMode}` : ""
        )}
        style={imgStyle}
      >
        <img
          src={src}
          alt="Reminder Media"
          className="w-full h-full object-contain pointer-events-none"
        />
      </div>
    );
  };

  const transitionType = reminder.transition || 'fade';
  
  const getTransitionVariants = (type: string) => {
    switch (type) {
      case 'slide-left':
        return {
          initial: { opacity: 0, x: 100, scale: 1 },
          animate: { opacity: 1, x: 0, scale: 1 },
          exit: { opacity: 0, x: -100, scale: 1 }
        };
      case 'slide-right':
        return {
          initial: { opacity: 0, x: -100, scale: 1 },
          animate: { opacity: 1, x: 0, scale: 1 },
          exit: { opacity: 0, x: 100, scale: 1 }
        };
      case 'zoom':
        return {
          initial: { opacity: 0, scale: 0.8, x: 0 },
          animate: { opacity: 1, scale: 1, x: 0 },
          exit: { opacity: 0, scale: 0.8, x: 0 }
        };
      case 'fade':
      default:
        return {
          initial: { opacity: 0, scale: 0.96, x: 0 },
          animate: { opacity: 1, scale: 1, x: 0 },
          exit: { opacity: 0, scale: 0.96, x: 0 }
        };
    }
  };

  const variants = getTransitionVariants(transitionType);

  return (
    <>
      <style>{`
        @keyframes card-marquee-scroll {
          0% { transform: translateX(0%); }
          100% { transform: translateX(-50%); }
        }
        .card-marquee-container {
          overflow: hidden;
          white-space: nowrap;
          width: 100%;
          display: block;
        }
        .card-marquee-content {
          display: inline-block;
          animation: card-marquee-scroll 20s linear infinite;
          will-change: transform;
        }
      `}</style>
      <motion.div
        key={reminder.id}
        initial={variants.initial}
        animate={variants.animate}
        exit={variants.exit}
        transition={{ duration: 0.45, ease: "easeOut" }}
        className={cn(
          "flex-grow flex p-6 sm:p-10 rounded-[36px] relative overflow-hidden transition-all duration-500 select-none min-h-[140px] items-center justify-center",
          reminder.bgColor || reminder.bgGradient ? "" : presets.bg,
          borderClasses
        )}
        style={cardStyle}
      >
        {/* 1. Background Pattern Overlay */}
        {bgPattern !== 'none' && (
          <div 
            className={cn(
              "absolute inset-0 pointer-events-none z-0 transition-opacity",
              bgPattern === 'islamic' ? "islamic-pattern-overlay" :
              bgPattern === 'dots' ? "bg-[radial-gradient(ellipse_at_center,_var(--tw-gradient-stops))] from-neutral-500/10 via-transparent to-transparent bg-[size:10px_10px]" :
              "bg-[linear-gradient(to_right,#80808012_1px,transparent_1px),linear-gradient(to_bottom,#80808012_1px,transparent_1px)] bg-[size:20px_20px]"
            )}
            style={{ opacity: bgPatternOpacity }}
          />
        )}

        {/* 2. Background Uploaded/URL Images */}
        {bgImages.map(img => {
          const src = resolveImgSrc(img);
          if (!src) return null;
          return (
            <img
              key={img.id}
              src={src}
              alt="Background pattern"
              className={cn(
                "absolute inset-0 w-full h-full object-cover pointer-events-none z-0 transition-all",
                img.blendMode && img.blendMode !== 'none' ? `mix-blend-${img.blendMode}` : "opacity-15",
                img.shape === 'circle' ? "rounded-full" : ""
              )}
              style={{ 
                opacity: (img.width ? img.width / 100 : 0.15),
                padding: img.padding ? `${img.padding}px` : undefined
              }}
            />
          );
        })}

        {/* 3. Watermark */}
        {renderWatermark()}

        {/* 5. Main Content Layout (Texts and Flow Images) */}
        <div 
          className={cn(
            "w-full h-full flex relative z-10 items-center justify-center",
            layout === 'flex-row' ? "flex-row" :
            layout === 'flex-row-reverse' ? "flex-row-reverse" :
            layout === 'flex-col-reverse' ? "flex-col-reverse" :
            layout === 'overlay' ? "relative" : "flex-col",
            gapClass
          )}
        >
          {/* Left media block */}
          {leftImages.length > 0 && (
            <div className="flex flex-col gap-2 shrink-0">
              {leftImages.map(renderImageItem)}
            </div>
          )}

          {/* Vertical group for Top images, Texts, and Bottom images */}
          <div className="flex-grow flex flex-col justify-center w-full gap-3">
            {topImages.length > 0 && (
              <div className="flex flex-row gap-2 justify-center flex-wrap">
                {topImages.map(renderImageItem)}
              </div>
            )}

            {/* Texts blocks list */}
            <div className="space-y-2 w-full flex flex-col justify-center">
              {texts.map((t) => {
                const textStyle: React.CSSProperties = {};
                if (t.color) {
                  textStyle.color = t.color;
                }
                
                if (t.glow) {
                  const glowColor = t.color || "var(--md-sys-color-primary)";
                  textStyle.textShadow = `0 0 10px ${glowColor}, 0 0 20px ${glowColor}`;
                }

                // Preset text style matching standard categories
                const isTitle = t.type === 'title';
                const isSubtitle = t.type === 'subtitle';
                const isCaption = t.type === 'caption';
                
                const defaultColorClass = t.color ? "" : (
                  isTitle ? "text-[var(--md-sys-color-on-surface)]" :
                  isSubtitle ? "text-[var(--md-sys-color-primary)] dark:text-[var(--md-sys-color-secondary)]" :
                  isCaption ? "text-[var(--md-sys-color-on-surface-variant)]/60" :
                  "text-[var(--md-sys-color-on-surface-variant)]"
                );

                if (t.marquee) {
                  return (
                    <div 
                      key={t.id} 
                      className={cn(
                        "card-marquee-container",
                        getFontSizeClass(t.size, isTvMode),
                        getFontFamilyClass(t.font),
                        getFontWeightClass(t.weight),
                        defaultColorClass,
                        isTitle ? "tracking-wide uppercase mb-1 font-black" :
                        isSubtitle ? "tracking-widest uppercase mb-1" : ""
                      )}
                      style={textStyle}
                    >
                      <div className="card-marquee-content">
                        {t.content}
                        <span className="opacity-40 px-12">&bull;</span>
                        {t.content}
                        <span className="opacity-40 px-12">&bull;</span>
                      </div>
                    </div>
                  );
                }

                return (
                  <div
                    key={t.id}
                    className={cn(
                      getFontSizeClass(t.size, isTvMode),
                      getFontFamilyClass(t.font),
                      getFontWeightClass(t.weight),
                      getTextAlignClass(t.align),
                      defaultColorClass,
                      isTitle ? "tracking-wide uppercase mb-1 font-black" :
                      isSubtitle ? "tracking-widest uppercase mb-1" : ""
                    )}
                    style={textStyle}
                  >
                    {t.content}
                  </div>
                );
              })}
            </div>

            {/* Countdown Widget */}
            {timeLeft && (
              <div className={cn("flex flex-col items-center mt-4 mb-2 z-10 w-full", isTvMode ? "gap-4" : "gap-1")}>
                {reminder.countdownLabel && (
                  <div className={cn(
                    "font-sans font-medium text-center opacity-85 tracking-wide",
                    isTvMode ? "text-xl" : "text-[10px]"
                  )}>
                    {reminder.countdownLabel}
                  </div>
                )}
                <div className="flex flex-row items-center justify-center gap-2">
                  {[
                    { value: timeLeft.days, label: language === 'ms' ? 'Hari' : 'Days' },
                    { value: timeLeft.hours, label: language === 'ms' ? 'Jam' : 'Hours' },
                    { value: timeLeft.minutes, label: language === 'ms' ? 'Min' : 'Mins' },
                    { value: timeLeft.seconds, label: language === 'ms' ? 'Saat' : 'Secs' },
                  ].map((item, idx) => (
                    <React.Fragment key={idx}>
                      <div className={cn(
                        "flex flex-col items-center justify-center bg-black/15 dark:bg-white/10 border border-white/10 rounded-2xl shadow-inner",
                        isTvMode ? "p-3 min-w-[100px] h-[90px]" : "p-1 min-w-[44px] h-[36px]"
                      )}>
                        <span className={cn("font-mono font-bold leading-none", isTvMode ? "text-3xl" : "text-sm")}>
                          {String(item.value).padStart(2, '0')}
                        </span>
                        <span className={cn("font-sans uppercase opacity-60 tracking-wider font-semibold", isTvMode ? "text-[10px] mt-1" : "text-[6px] mt-0.5")}>
                          {item.label}
                        </span>
                      </div>
                      {idx < 3 && (
                        <span className={cn("font-mono font-bold opacity-60", isTvMode ? "text-3xl mx-1" : "text-sm mx-0.5")}>
                          :
                        </span>
                      )}
                    </React.Fragment>
                  ))}
                </div>
              </div>
            )}

            {bottomImages.length > 0 && (
              <div className="flex flex-row gap-2 justify-center flex-wrap">
                {bottomImages.map(renderImageItem)}
              </div>
            )}
          </div>

          {/* Right media block */}
          {rightImages.length > 0 && (
            <div className="flex flex-col gap-2 shrink-0">
              {rightImages.map(renderImageItem)}
            </div>
          )}
        </div>
      </motion.div>
    </>
  );
}
